# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pre-prod-build

on:
  push:
    branches: [ pre-prod ]
  pull_request:
    branches: [ pre-prod ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - name: Run ESLint
      uses: ninosaurus/eslint-check@v5
      with:
       eslint-config-path: "./application/assets/js/.eslintrc.json"
       custom-directory: "./application"
       repo-token: ${{secrets.GITHUB_TOKEN}}
    - uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_API_NAME}} #Must be unique in Heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}